services:

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/lib/postgresql
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 1s
      timeout: 5s
      retries: 10


  app:
    image: morfinall/nodejs2024q3-service-app3:latest
    container_name: app
    restart: always
    env_file: .env
    ports:
      - '${PORT}:${PORT}'
    networks:
      - app-network
    command: sh -c "npx prisma migrate deploy && node dist/src/main.js"

networks:
  app-network:
    driver: ${DRIVER}

volumes:
  postgres_data:
  postgres_logs: