version: '3.8'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: my_database_user
      POSTGRES_PASSWORD: my_secure_password
      POSTGRES_DB: home_library_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/log/postgresql
    networks:
      - app_network

  app:
    build:
      context: .
      target: development
    command: npm run start:dev
    restart: always
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
  db_logs:
