version: '3.8'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/log/postgresql
    networks:
      - app_network

  app:
    build: .
    command: npm run start:dev
    restart: always
    ports:
      - '4000:4000'
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: your_db_user
      DATABASE_PASSWORD: your_db_password
      DATABASE_NAME: your_db_name
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
  db_logs:
